### ISSUE TITLE
Mongodb URL setting

### ISSUE THREAD

**Issue by l4es** [urcoilbisurco/Aurora-Server#2]
Hi Francesco,

I'm interested in your project but I'm quite new to Javascript. I createed the app/_env.js as in the README of the project and got the following error: 

09:56 $ npm run start
...
Starting child process with 'node index.js'
Ignoring directory '/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/webapp'.
Ignoring directory '/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/node_modules'.
Watching directory '/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server' for changes.
Press rs for restarting the process.
module.js:549
    throw err;
    ^

Error: Cannot find module './_env'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/index.js:9:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Program node index.js exited with code 1

Starting child process with 'node index.js'
...

I then copied the _env.js file to the root folder then I got another error:
10:00 $ npm run start
...
/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/utils/db.js:8
  db.users= db.collection("users");
               ^

TypeError: Cannot read property 'collection' of undefined
    at /home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/utils/db.js:8:16
    at /home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/node_modules/mongodb/lib/mongo_client.js:486:21
    at module.exports (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/node_modules/mongodb/lib/url_parser.js:15:12)
    at connect (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/node_modules/mongodb/lib/mongo_client.js:485:3)
    at Function.MongoClient.connect (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/node_modules/mongodb/lib/mongo_client.js:250:3)
    at Object.<anonymous> (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/utils/db.js:6:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/routes/routes.js:4:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/xxx/Workspace/Edu/SmartHome/Aurora/Aurora-Server/index.js:11:13)
Program node index.js exited with code 1

Could you please help me to setup the _env.js file correctly ?

nodejs: v8.11.3
npm: 6.2.0

Thanks and best regards,
Pascal.

**Comment by urcoilbisurco** [comment]
I just updated the README with the fix for the _env.js file (it should be in the root of the project, not on /app). Thanks!

For the second error, did you create a new DB in mongodb and updated the URL (likely localhost:27017/*database_name*) in _env.js?

**Comment by l4es** [comment]
Hello,
I've just create a database named toto and updated my _env.js at as following:

var env={
  production:true,
  port:80,
  mongo:"mongodb://localhost:27017/toto",
  mqtt_server:"mqtt://localhost:1883",
  broker:{
    mongo_url:"mongodb://localhost:27017/",
    port:1883
  },
  weather:{
    token:"Your darksky.net API key",
    location:"lat,long",
  },
}
module.exports=env;

Could you tell me something wrong? And can you give an example of  mqtt_server as well?

Many thanks,
Pascal

**Comment by urcoilbisurco** [comment]
This is the current _env.js that I'm using on my local environment:

>var env={
    production:false,
    port:3456,
    mongo: "mongodb://localhost:27017/test_aurora",
    mqtt_server:"mqtt://localhost:1883",
    socket_server: "http://localhost:3456",
    auth: {
      saltRounds: 10,
    },
    broker:{
      mongo_url:"mongodb://localhost:27017/",
      port:1883
    },
    weather:{
      token:"Your darksky.net API key",
      location:"lat,long",
    },
  }

In the README.md were missing some fields, like socket_server and auth. 

Let me know if it's working!
Francesco

**Comment by l4es** [comment]
Hi Francesco, 
I works now, thanks for your helps. With that, I can go further in my studying of this project as well as Javascript :).

BR,
Khang
